const codeList = [
  { "groupCode": "ADLT_LVL_CD", "groudName": "성인 등급 코드", "code": "01", "codeName": "Adult Movie Y" },
  { "groupCode": "ADLT_LVL_CD", "groudName": "성인 등급 코드", "code": "03", "codeName": "Pink Movie Y" },
  { "groupCode": "BBNR_TYP_CD", "groudName": "빅배너 유형 코드", "code": "10", "codeName": "이미지형" },
  { "groupCode": "BBNR_TYP_CD", "groudName": "빅배너 유형 코드", "code": "20", "codeName": "하프형" },
  { "groupCode": "BBNR_TYP_CD", "groudName": "빅배너 유형 코드", "code": "30", "codeName": "영상형" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "10", "codeName": "장르홈" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "20", "codeName": "메뉴 블록" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "30", "codeName": "콘텐츠 편성" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "50", "codeName": "실시간 채널 편성" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "60", "codeName": "앱 편성" },
  { "groupCode": "BLK_TYP_CD", "groudName": "블록 유형 코드", "code": "70", "codeName": "이벤트 편성" },
  { "groupCode": "BNR_EXPS_MTHD_CD", "groudName": "배너 노출 방식 코드", "code": "10", "codeName": "텍스트" },
  { "groupCode": "BNR_EXPS_MTHD_CD", "groudName": "배너 노출 방식 코드", "code": "20", "codeName": "이미지" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "1", "codeName": "xpg팝업" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "2", "codeName": "browse" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "3", "codeName": "pop_adv" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "4", "codeName": "로컬경로" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "9", "codeName": "ACAP" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "10", "codeName": "LIVE 방송" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "12", "codeName": "에코스시템" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "16", "codeName": "플래쉬" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "17", "codeName": "UI App(신규UI My고객센터)" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "18", "codeName": "안드로이드" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "19", "codeName": "패키지" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "20", "codeName": "NextUI(고객센터)" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "21", "codeName": "메뉴 바로가기" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "22", "codeName": "CW호출" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "23", "codeName": "UI APP(UI5.0)" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "24", "codeName": "TV APP(MeTV)" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "25", "codeName": "실시간채널" },
  { "groupCode": "CALL_TYP_CD", "groudName": "호출 유형 코드", "code": "26", "codeName": "시놉시스" },
  { "groupCode": "CHRTR_MENU_CAT_CD", "groudName": "캐릭터 메뉴 카테고리 코드", "code": "10", "codeName": "시즌별" },
  { "groupCode": "CHRTR_MENU_CAT_CD", "groudName": "캐릭터 메뉴 카테고리 코드", "code": "20", "codeName": "동요/율동" },
  { "groupCode": "CHRTR_MENU_CAT_CD", "groudName": "캐릭터 메뉴 카테고리 코드", "code": "30", "codeName": "영화" },
  { "groupCode": "CHRTR_MENU_CAT_CD", "groudName": "캐릭터 메뉴 카테고리 코드", "code": "40", "codeName": "앱" },
  { "groupCode": "CHRTR_MENU_CAT_CD", "groudName": "캐릭터 메뉴 카테고리 코드", "code": "50", "codeName": "키즈엔터테인먼트" },
  { "groupCode": "CMPGN_ITLK_TYP_CD", "groudName": "캠페인 연동 유형 코드", "code": "1", "codeName": "편성정보" },
  { "groupCode": "CMPGN_ITLK_TYP_CD", "groudName": "캠페인 연동 유형 코드", "code": "2", "codeName": "타겟배너" },
  { "groupCode": "CMPGN_ITLK_TYP_CD", "groudName": "캠페인 연동 유형 코드", "code": "3", "codeName": "타겟메뉴" },
  { "groupCode": "CNTS_TYP_CD", "groudName": "콘텐츠 유형 코드", "code": "10", "codeName": "시리즈" },
  { "groupCode": "CNTS_TYP_CD", "groudName": "콘텐츠 유형 코드", "code": "20", "codeName": "에피소드" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "1", "codeName": "xpg팝업" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "2", "codeName": "browse" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "3", "codeName": "pop_adv" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "4", "codeName": "로컬경로" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "9", "codeName": "ACAP" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "10", "codeName": "LIVE 방송" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "12", "codeName": "에코스시템" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "16", "codeName": "플래쉬" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "17", "codeName": "UI App(신규UI My고객센터)" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "18", "codeName": "안드로이드" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "19", "codeName": "패키지" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "20", "codeName": "NextUI(고객센터)" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "21", "codeName": "메뉴 바로가기" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "22", "codeName": "CW호출" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "23", "codeName": "UI APP(UI5.0)" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "24", "codeName": "TV APP(MeTV)" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "25", "codeName": "실시간채널" },
  { "groupCode": "EVT_COMT_CALL_TYP_CD", "groudName": "이벤트 코멘트 호출 유형 코드", "code": "26", "codeName": "시놉시스" },
  { "groupCode": "EVT_COMT_EXPS_MTHD_CD", "groudName": "이벤트 코멘트 노출 방식 코드", "code": "10", "codeName": "텍스트" },
  { "groupCode": "EVT_COMT_EXPS_MTHD_CD", "groudName": "이벤트 코멘트 노출 방식 코드", "code": "20", "codeName": "이미지" },
  { "groupCode": "EXPS_MTHD_CD", "groudName": "노출 방식 코드", "code": "10", "codeName": "콘텐츠" },
  { "groupCode": "EXPS_MTHD_CD", "groudName": "노출 방식 코드", "code": "20", "codeName": "블록" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "VIEW_ALL", "codeName": "전체메뉴" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "POP_VOD", "codeName": "인기VOD" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "MY_BTV", "codeName": "마이 B tv" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "M_VIEW", "codeName": "멀티뷰" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "LIVE_TV", "codeName": "실시간TV" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "FNJ", "codeName": "펀&조이" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "ALL_APPS", "codeName": "ALL APPS" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "B_SHOP", "codeName": "B쇼핑" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "CUG_REC", "codeName": "CUG추천메뉴" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_01", "codeName": "마이 Btv" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_02", "codeName": "월정액" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_03", "codeName": "홈" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_04", "codeName": "영화/시리즈" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_05", "codeName": "TV다시보기" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_06", "codeName": "애니" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_07", "codeName": "키즈" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_08", "codeName": "다큐/라이프/교육" },
  { "groupCode": "GNB_TYP_CD", "groudName": "GNB 유형 코드", "code": "U5_09", "codeName": "검색" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "10", "codeName": "월정액" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "20", "codeName": "장르메뉴" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "30", "codeName": "캐릭터" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "40", "codeName": "놀이학습" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "50", "codeName": "채널" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "60", "codeName": "시청습관 관리" },
  { "groupCode": "KIDSZ_GNB_CD", "groudName": "키즈존 GNB 코드", "code": "70", "codeName": "살아있는 동화" },
  { "groupCode": "KIDS_AGE_CD", "groudName": "키즈 연령 코드", "code": "01", "codeName": "3세 미만" },
  { "groupCode": "KIDS_AGE_CD", "groudName": "키즈 연령 코드", "code": "02", "codeName": "4세~6세" },
  { "groupCode": "KIDS_AGE_CD", "groudName": "키즈 연령 코드", "code": "03", "codeName": "7세 이상" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "01", "codeName": "우리말" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "02", "codeName": "한글자막" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "03", "codeName": "영어자막" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "04", "codeName": "영어더빙" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "05", "codeName": "중국어더빙" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "15", "codeName": "외국어자막" },
  { "groupCode": "LAG_CAPT_TYP_CD", "groudName": "언어 자막 유형 코드", "code": "13", "codeName": "기타" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "1", "codeName": "공통메뉴(2.0+Legacy)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "10", "codeName": "스마트리모콘" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "11", "codeName": "핫메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "12", "codeName": "삼성제외메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "13", "codeName": "bstore신청메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "14", "codeName": "추천시스템" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "15", "codeName": "SKTDRM미전환메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "16", "codeName": "YouTube노출(핫라인)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "17", "codeName": "핫메뉴(YouTube구분)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "18", "codeName": "YouTube패치메뉴노출" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "19", "codeName": "휴대폰결제제외메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "2", "codeName": "IPTV2.0전용" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "20", "codeName": "YouTube CurationList" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "21", "codeName": "신규UI선택적패치" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "22", "codeName": "신규UI전용" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "23", "codeName": "핫메뉴(신규UI선택적패치)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "24", "codeName": "핫메뉴(하위메뉴용)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "25", "codeName": "CS선택적패치" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "26", "codeName": "프로모션롤링배너" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "27", "codeName": "메뉴고지" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "28", "codeName": "실시간 채널UI" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "29", "codeName": "19영화(핑크무비)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "3", "codeName": "Legacy전용" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "30", "codeName": "19플러스" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "4", "codeName": "쇼핑2차전용" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "5", "codeName": "노출안함(임시)" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "6", "codeName": "bstore 제외메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "7", "codeName": "bstore전용메뉴" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "8", "codeName": "다중자막전용" },
  { "groupCode": "MENU_EXPS_PROP_CD", "groudName": "메뉴 노출 속성 코드", "code": "9", "codeName": "캐치온디맨드" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "000", "codeName": "영화" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "001", "codeName": "드라마" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "002", "codeName": "예능" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "003", "codeName": "시사교양" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "004", "codeName": "다큐" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "005", "codeName": "키즈" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "006", "codeName": "애니" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "007", "codeName": "스포츠" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "008", "codeName": "교육" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "009", "codeName": "성인(에로스)" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "011", "codeName": "클립일반" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "012", "codeName": "클립뉴스" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "013", "codeName": "클립스포츠" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "021", "codeName": "콘텐츠팩" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "022", "codeName": "관련상품팩" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "023", "codeName": "360VR" },
  { "groupCode": "META_TYP_CD", "groudName": "메타 유형 코드", "code": "024", "codeName": "살아있는동화" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "10", "codeName": "일반" }, // PPV
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "20", "codeName": "전편구매" }, // PPS
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "30", "codeName": "월정액" }, // VOD PPM
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "34", "codeName": "복합 VOD PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "35", "codeName": "복합 PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "41", "codeName": "패키지" }, // PPP
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "50", "codeName": "VAS PPV" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "60", "codeName": "VAS PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "80", "codeName": "채널 PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "110", "codeName": "Mob PPV" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "120", "codeName": "Mob PPS" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "130", "codeName": "Mob VOD PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "132", "codeName": "Mob VOD PPM 기간권" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "133", "codeName": "Mob VOD PPM 체험권" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "134", "codeName": "Mob 복합 VOD PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "135", "codeName": "Mob 복합 PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "141", "codeName": "Mob PPP" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "180", "codeName": "Mob 채널 PPM" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "181", "codeName": "Mob 기본 상품" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "182", "codeName": "Mob 채널 PPM 기간권" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "183", "codeName": "Mob 채널 PPM 체험권" },
  { "groupCode": "PRD_TYP_CD", "groudName": "상품 유형 코드", "code": "42", "codeName": "관련상품 PPP" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "00", "codeName": "감독(연출)" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "01", "codeName": "주연" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "02", "codeName": "조연" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "03", "codeName": "특별출연" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "04", "codeName": "우리말목소리" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "13", "codeName": "외국어목소리" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "05", "codeName": "작가" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "06", "codeName": "그림작가" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "07", "codeName": "진행" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "10", "codeName": "출연" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "09", "codeName": "게스트" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "12", "codeName": "등장캐릭터" },
  { "groupCode": "PRS_ROLE_CD", "groudName": "인물 역할 코드", "code": "99", "codeName": "기타" },
  { "groupCode": "PST_EXPS_TYP_CD", "groudName": "포스터 노출 유형 코드", "code": "10", "codeName": "가로" },
  { "groupCode": "PST_EXPS_TYP_CD", "groudName": "포스터 노출 유형 코드", "code": "20", "codeName": "세로" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "10", "codeName": "SD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "20", "codeName": "HD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "25", "codeName": "FULL HD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "30", "codeName": "UHD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "35", "codeName": "HDR" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "100", "codeName": "OA" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "105", "codeName": "LD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "110", "codeName": "SD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "120", "codeName": "HD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "125", "codeName": "FULL HD" },
  { "groupCode": "RSLU_TYP_CD", "groudName": "해상도 유형 코드", "code": "130", "codeName": "UHD" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "1", "codeName": "xpg팝업" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "2", "codeName": "browse" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "3", "codeName": "pop_adv" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "4", "codeName": "로컬경로" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "9", "codeName": "ACAP" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "10", "codeName": "LIVE 방송" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "12", "codeName": "에코스시템" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "16", "codeName": "플래쉬" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "17", "codeName": "UI App(신규UI My고객센터)" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "18", "codeName": "안드로이드" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "19", "codeName": "패키지" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "20", "codeName": "NextUI(고객센터)" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "21", "codeName": "메뉴 바로가기" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "22", "codeName": "CW호출" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "23", "codeName": "UI APP(UI5.0)" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "24", "codeName": "TV APP(MeTV)" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "25", "codeName": "실시간채널" },
  { "groupCode": "SALES_COMT_CALL_TYP_CD", "groudName": "세일즈 코멘트 호출 유형 코드", "code": "26", "codeName": "시놉시스" },
  { "groupCode": "SALES_COMT_EXPS_MTHD_CD", "groudName": "세일즈 코멘트 노출 방식 코드", "code": "10", "codeName": "텍스트" },
  { "groupCode": "SALES_COMT_EXPS_MTHD_CD", "groudName": "세일즈 코멘트 노출 방식 코드", "code": "20", "codeName": "이미지" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "0", "codeName": "0: 2단리스트" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "10", "codeName": "10: 이미지공지타입1" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "11", "codeName": "11: 이미지공지타입2" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "12", "codeName": "12:시청제한" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "13", "codeName": "13: 전체메뉴" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "14", "codeName": "14: 설정(업그레이드)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "15", "codeName": "15: 인증설정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "16", "codeName": "16: 개인메뉴" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "17", "codeName": "17: 서비스설정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "19", "codeName": "18: 인터넷설정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "19", "codeName": "19: 화면채널설정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "2", "codeName": "몰라" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "20", "codeName": "20: 기기정보" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "21", "codeName": "21: 구매내역" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "22", "codeName": "22: 선불권내역" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "23", "codeName": "23: JOY" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "24", "codeName": "24: 스타화보" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "25", "codeName": "25: 마이채널" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "26", "codeName": "26: 사내방송" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "27", "codeName": "27:메뉴리모콘코지" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "28", "codeName": "28:심벌이미지팝업" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "29", "codeName": "29:IPTV" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "3", "codeName": "3: 뉴스" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "30", "codeName": "30:온라인속성" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "31", "codeName": "31:시청도우미" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "32", "codeName": "32:스위칭메뉴" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "33", "codeName": "33:녹화프로그램" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "35", "codeName": "35:IPTV설정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "36", "codeName": "36:구매내역(VOD)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "37", "codeName": "37:구매내역(IPTV)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "38", "codeName": "38:채널EPG(실시간방송)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "39", "codeName": "39:FULL EPG(실시간방송)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "40", "codeName": "40:더미리스트타입" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "41", "codeName": "41:모자익 타입" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "42", "codeName": "42:쇼핑도움말" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "43", "codeName": "43:쇼핑이용약관" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "44", "codeName": "44:BIG 이미지 타입" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "45", "codeName": "45:가나다순" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "46", "codeName": "46:IPTV 방송" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "47", "codeName": "47:마이페이지" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "48", "codeName": "48:쇼핑구매내역(IPTV2.0)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "49", "codeName": "49:찜한상품" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "5", "codeName": "5: 1단리스트" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "50", "codeName": "50:나의정보수정" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "51", "codeName": "51:메뉴에서시놉이동" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "52", "codeName": "52:메뉴에서그리드이동(텍스트)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "53", "codeName": "53:메뉴에서그리드이동(이미지)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "54", "codeName": "54:베스트상품" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "55", "codeName": "55:TV쇼핑" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "56", "codeName": "56:학교IPTV" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "57", "codeName": "57:검색" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "58", "codeName": "58:추천시스템" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "59", "codeName": "59:B2B방송" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "60", "codeName": "60:펀앤조이이동" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "61", "codeName": "61:멀티캐스트조인" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "62", "codeName": "62:플래쉬" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "63", "codeName": "63:유투브큐레이션" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "64", "codeName": "64:찜목록(신규UI 전체메뉴)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "65", "codeName": "65:유투브(신규UI 전체메뉴)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "66", "codeName": "66:고객친화영역(My고객센터)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "67", "codeName": "67:프로모션(My고객센터)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "68", "codeName": "68:동영상가이드(SB_My고객센터)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "69", "codeName": "69:메뉴에서메뉴이동" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "7", "codeName": "7: 시청채널" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "70", "codeName": "70:추천관" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "71", "codeName": "71:MyBtv메뉴" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "72", "codeName": "72:포인트쿠폰함" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "73", "codeName": "73:쿠폰함" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "74", "codeName": "74:B포인트" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "75", "codeName": "75:키즈존 게이트" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "76", "codeName": "76:키즈존 공지사항/이벤트" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "77", "codeName": "77:키즈존 소개" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "78", "codeName": "78:키즈존 FAQ" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "79", "codeName": "79:키즈존 월정액안내" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "8", "codeName": "8: 예약채널" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "80", "codeName": "80:테마추천메뉴(NextUI)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "81", "codeName": "81:CW추천메뉴_Block(NextUI)" },
  { "groupCode": "SCN_MTHD_CD", "groudName": "상영 방식 코드", "code": "82", "codeName": "82:CW추천메뉴_그리드(NextUI)" },
  { "groupCode": "SND_TYP_CD", "groudName": "음향 유형 코드", "code": "1", "codeName": "STEREO" },
  { "groupCode": "SND_TYP_CD", "groudName": "음향 유형 코드", "code": "2", "codeName": "5.1(DOLBY)" },
  { "groupCode": "SND_TYP_CD", "groudName": "음향 유형 코드", "code": "3", "codeName": "ATMOS" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "01", "codeName": "시즌" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "02", "codeName": "타이틀" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "04", "codeName": "콘텐츠팩" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "05", "codeName": "콘텐츠팩" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "06", "codeName": "관련상품팩" },
  { "groupCode": "SRIS_TYP_CD", "groudName": "시리즈 유형 코드", "code": "07", "codeName": "더빙+자막팩" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "1", "codeName": "영상집중형" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "2", "codeName": "포탈형(우먼스타일)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "3", "codeName": "포탈형(여행)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "4", "codeName": "포탈형(게임TV)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "5", "codeName": "포탈형(쇼핑)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "6", "codeName": "포탈형(부가서비스)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "10", "codeName": "프리미엄AD" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "11", "codeName": "지상파" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "12", "codeName": "서브아이템" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "13", "codeName": "프로모션메뉴" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "14", "codeName": "학교IPTV" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "15", "codeName": "VDI" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "16", "codeName": "찜목록(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "17", "codeName": "VOD(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "18", "codeName": "실시간TV(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "19", "codeName": "펀엔조이(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "20", "codeName": "쇼핑(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "21", "codeName": "세일&이벤트(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "22", "codeName": "프로모션(신규UI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "23", "codeName": "스마트박스Home구분" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "24", "codeName": "인기VOD(2nd Device)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "25", "codeName": "스마트박스TOP20" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "26", "codeName": "마이Btv(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "27", "codeName": "TV앱(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "28", "codeName": "설정(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "29", "codeName": "편성표(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "30", "codeName": "고객센터(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "31", "codeName": "이슈스타(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "32", "codeName": "테마추천관(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "33", "codeName": "무비파인더(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "34", "codeName": "1단메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "35", "codeName": "2단메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "36", "codeName": "3단메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "38", "codeName": "검색메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "39", "codeName": "월정액 메뉴(키즈존고도화)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "40", "codeName": "VAS 메뉴(키즈존고도화)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "41", "codeName": "5단메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "42", "codeName": "9단메뉴(NextUI 전체메뉴)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "51", "codeName": "고객서비스-공지알림(UI5.0)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "52", "codeName": "고객서비스-이벤트(UI5.0)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "53", "codeName": "고객서비스-이용가이드(UI5.0)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "54", "codeName": "고객서비스-기기연결관리(UI5.0)" },
  { "groupCode": "SVC_PROP_CD", "groudName": "서비스 속성 코드", "code": "55", "codeName": "고객서비스-설정(UI5.0)" },
  { "groupCode": "SYNON_TYP_CD", "groudName": "진입할 시놉시스 유형", "code": "01", "codeName": "단편 시놉시스" },
  { "groupCode": "SYNON_TYP_CD", "groudName": "진입할 시놉시스 유형", "code": "02", "codeName": "시즌 시놉시스" },
  { "groupCode": "SYNON_TYP_CD", "groudName": "진입할 시놉시스 유형", "code": "03", "codeName": "게이트웨이 시놉시스" },
  { "groupCode": "SYNON_TYP_CD", "groudName": "진입할 시놉시스 유형", "code": "04", "codeName": "VOD + 관련상품 시놉시스" },
  { "groupCode": "UGUID_TYP_CD", "groudName": "이용가이드 유형 코드", "code": "10", "codeName": "텍스트" },
  { "groupCode": "UGUID_TYP_CD", "groudName": "이용가이드 유형 코드", "code": "20", "codeName": "이미지" },
  { "groupCode": "WAT_LVL_CD", "groudName": "시청 등급 코드", "code": "0", "codeName": "전체 관람가" },
  { "groupCode": "WAT_LVL_CD", "groudName": "시청 등급 코드", "code": "7", "codeName": "7세 관람가" },
  { "groupCode": "WAT_LVL_CD", "groudName": "시청 등급 코드", "code": "12", "codeName": "12세 관람가" },
  { "groupCode": "WAT_LVL_CD", "groudName": "시청 등급 코드", "code": "15", "codeName": "15세 관람가" },
  { "groupCode": "WAT_LVL_CD", "groudName": "시청 등급 코드", "code": "19", "codeName": "19세 관람가" }
];

export function getCode(groupCode, code) {
  // console.log(groupCode, code);

  const newArr = codeList.filter(function (item) {
    return item.groupCode === String(groupCode).toUpperCase() && item.code === String(code);
  });
  // console.log("Filter results:",newArr);

  return newArr;
}

export function getCodeName(groupCode, code) {
  // console.log(groupCode, code);
  /*
  const newArr = codeList.filter(function(item){    
    return item.groupCode === String(groupCode).toUpperCase() && item.code === String(code);
  });  
  */
  const newArr = getCode(groupCode, code);

  if (newArr.length !== 1) {
    if (newArr.length === 0) {
      return null;
    } else if (newArr.length > 1) {
      return "[ERROR] Dupliated Code";
    }
  }

  // console.log("Filter results:", newArr[0].codeName);
  return newArr[0].codeName;
}

export function getCodeGroup(groupCode) {
  const newArr = codeList.filter(function (item) {
    return item.groupCode === String(groupCode).toUpperCase();
  });

  return newArr;
}